# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. 
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: raviriley/agency-jekyll-theme
#theme: jekyll-agency

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/canterbury-soccer" # the subpath of your site, e.g. /blog

title      : Canterbury Soccer Club
email      : canterburysoccer@gmail.com #this is also the email contact forms will go to
description: "The Canterbury Soccer Club has been operating in Ottawa, Canada for 41 years to provide non-competitive recreational soccer to youth between the ages of 5 and 12 years old in the Canterbury and Alta Vista community of Ottawa. The club's goal is to ensure that our youth HAVE FUN while all getting an equal opportunity to play the game."
author     : Chris Cooper
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme
